$(function(){
    $('.loading1>img').on('load',function(){
        $('.loader').fadeOut(400)
        $('#div-body').css({
            'overflow-y':'auto',
        })
        $('.head-name').slideDown(600)
    })
    $('.loading1').hide()
})